# Generated by Django 6.0.4 on 2026-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0002_productmodel_alter_product_sku_product_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='report_category',
            new_name='category',
        ),
    ]
