# Generated by Django 6.0.4 on 2026-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0006_supplier_productunit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_product_brand_model'),
        ),
    ]
