# Generated by Django 6.0.4 on 2026-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0008_restructure_product_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='available', max_length=20),
        ),
    ]
