# Generated by Django 6.0.4 on 2026-06-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0013_deliveryrecord_deliveryitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
