# Generated by Django 6.0.4 on 2026-07-06 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0018_deliveryrecord_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.deliveryrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='bim_stock.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='bim_stock.productunit')),
                ('receiving_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.receivingrecord')),
            ],
            options={
                'ordering': ('-movement_date', '-crdate', '-pk'),
                'indexes': [models.Index(fields=['product', 'movement_date'], name='bim_stock_s_product_f9e922_idx'), models.Index(fields=['product_unit', 'movement_date'], name='bim_stock_s_product_eb6386_idx'), models.Index(fields=['movement_type', 'movement_date'], name='bim_stock_s_movemen_5c594a_idx')],
            },
        ),
    ]
