# Generated by Django 6.0.4 on 2026-07-06 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0019_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update'), ('reserved', 'Reserved'), ('reservation_released', 'Reservation Released')], max_length=40),
        ),
        migrations.CreateModel(
            name='ReservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('reserved_for', models.CharField(max_length=150)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('expected_release_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_stock_reservation_records', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reserved_at', '-reservation_number'),
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bim_stock.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='bim_stock.productunit')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bim_stock.reservationrecord')),
            ],
            options={
                'ordering': ('product__descript', 'product_unit__serial_number'),
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reservation_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.reservationrecord'),
        ),
    ]
