# Generated by Django 6.0.4 on 2026-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0020_alter_stockmovement_movement_type_reservationrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('sold', 'Sold'), ('repair', 'Repair'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
