# Generated by Django 6.0.4 on 2026-07-06 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0021_alter_productunit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update'), ('reserved', 'Reserved'), ('reservation_released', 'Reservation Released'), ('issued', 'Issued'), ('issue_returned', 'Issue Returned')], max_length=40),
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('issued_to', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('branch_or_site', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('return_reason', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issue_records', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_stock_issue_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issue_date', '-issue_number'),
            },
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bim_stock.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items', to='bim_stock.productunit')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bim_stock.issuerecord')),
            ],
            options={
                'ordering': ('product__descript', 'product_unit__serial_number'),
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='issue_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.issuerecord'),
        ),
    ]
