# Generated by Django 6.0.4 on 2026-07-06 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0023_alter_stockmovement_movement_type_repairrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update'), ('reserved', 'Reserved'), ('reservation_released', 'Reservation Released'), ('issued', 'Issued'), ('issue_returned', 'Issue Returned'), ('sent_to_repair', 'Sent To Repair'), ('repair_resolved', 'Repair Resolved'), ('repair_deactivated', 'Repair Deactivated'), ('client_returned_available', 'Client Returned Available'), ('client_returned_repair', 'Client Returned Repair')], max_length=40),
        ),
        migrations.CreateModel(
            name='ClientReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('received_from', models.CharField(blank=True, max_length=150)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('resolution', models.CharField(choices=[('available', 'Available'), ('repair', 'Repair')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_returns', to='bim_stock.deliveryrecord')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_client_return_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-return_date', '-return_number'),
            },
        ),
        migrations.CreateModel(
            name='ClientReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_return_items', to='bim_stock.deliveryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bim_stock.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_return_items', to='bim_stock.productunit')),
                ('client_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bim_stock.clientreturnrecord')),
            ],
            options={
                'ordering': ('product__descript', 'product_unit__serial_number'),
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='client_return_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.clientreturnrecord'),
        ),
    ]
