# Generated by Django 6.0.4 on 2026-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0025_client_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingrecord',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receivingrecord',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
