# Generated by Django 6.0.4 on 2026-07-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0026_receivingrecord_po_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingrecord',
            name='reference_number',
        ),
    ]
