# Generated by Django 6.0.4 on 2026-07-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0027_remove_receivingrecord_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerecord',
            name='branch_or_site',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='expected_return_date',
        ),
    ]
