# Generated by Django 6.0.4 on 2026-07-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0029_remove_repairrecord_expected_resolution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
