# Generated by Django 6.0.4 on 2026-07-20 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0030_deliveryitem_sale_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='receivingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='unique_receivingrecord_idempotency_key'),
        ),
    ]
