# Generated by Django 6.0.4 on 2026-07-20 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0031_receivingrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('sold', 'Sold'), ('repair', 'Repair'), ('inactive', 'Inactive'), ('removed', 'Removed')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update'), ('reserved', 'Reserved'), ('reservation_released', 'Reservation Released'), ('issued', 'Issued'), ('issue_returned', 'Issue Returned'), ('sent_to_repair', 'Sent To Repair'), ('repair_resolved', 'Repair Resolved'), ('repair_deactivated', 'Repair Deactivated'), ('client_returned_available', 'Client Returned Available'), ('client_returned_repair', 'Client Returned Repair'), ('removed', 'Removed')], max_length=40),
        ),
        migrations.CreateModel(
            name='RemovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('stolen', 'Stolen'), ('written_off', 'Written Off'), ('other', 'Other')], max_length=20)),
                ('removal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_removal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-removal_date', '-removal_number'),
            },
        ),
        migrations.CreateModel(
            name='RemovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bim_stock.product')),
                ('product_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='removal_item', to='bim_stock.productunit')),
                ('removal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bim_stock.removalrecord')),
            ],
            options={
                'ordering': ('product__descript', 'product_unit__serial_number'),
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='removal_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='bim_stock.removalrecord'),
        ),
    ]
