# Generated by Django 6.0.4 on 2026-08-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0032_alter_productunit_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreturnrecord',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientreturnrecord',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientreturnrecord',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_client_return_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientreturnrecord',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('cancelled', 'Cancelled')], default='recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='repairrecord',
            name='client_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_records', to='bim_stock.clientreturnrecord'),
        ),
        migrations.AlterField(
            model_name='repairrecord',
            name='resolution',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('inactive', 'Inactive'), ('sold', 'Returned to Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received'), ('receiving_cancelled', 'Receiving Cancelled'), ('delivered', 'Delivered'), ('delivery_cancelled', 'Delivery Cancelled'), ('manual_add', 'Manual Add'), ('manual_update', 'Manual Update'), ('reserved', 'Reserved'), ('reservation_released', 'Reservation Released'), ('issued', 'Issued'), ('issue_returned', 'Issue Returned'), ('sent_to_repair', 'Sent To Repair'), ('repair_resolved', 'Repair Resolved'), ('repair_deactivated', 'Repair Deactivated'), ('client_returned_available', 'Client Returned Available'), ('client_returned_repair', 'Client Returned Repair'), ('client_return_cancelled', 'Client Return Cancelled'), ('repair_returned_to_client', 'Repair Returned To Client'), ('removed', 'Removed')], max_length=40),
        ),
    ]
