"""
Django settings for bim project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads backend/.env into os.environ (if present) so every os.environ.get()
# call below - not just the ones read directly through `env` - picks up
# local overrides. Real deployments should set these as actual OS env vars
# instead of shipping a .env file.
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-*85%i(ofy9ff93u84@&*-6)w$wy0b)9cr7ft^^rya@s=blcwao",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe for LAN/production) if DJANGO_DEBUG is unset;
# set DJANGO_DEBUG=True in .env for local development.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

# Comma-separated in .env, e.g. DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.101
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'apps.core.apps.CoreConfig',
    'apps.accounts.apps.BimAccountsConfig',
    'apps.stock.apps.BimStockConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Filename only (lives at repo root, alongside BASE_DIR). Defaults to
        # 'db.sqlite3' for local dev; production sets DJANGO_DB_NAME=db_prod.sqlite3
        # via .env.production (see run_production.py) so the two never collide.
        'NAME': BASE_DIR.parent / env('DJANGO_DB_NAME', default='db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Local business timezone. This keeps admin date/time notes and default dates
# aligned with Beirut, Lebanon.
TIME_ZONE = 'Asia/Beirut'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# whitenoise serves STATIC_ROOT directly (compressed + cache-busted via a
# manifest) so no nginx/CDN is needed in front of runserver/gunicorn.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'module_launcher'
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.UsernameOrEmailBackend',
]

EMAIL_BACKEND = os.environ.get(
    "BIM_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("BIM_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("BIM_EMAIL_PORT", "587"))
EMAIL_USE_TLS = env_bool("BIM_EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.environ.get("BIM_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("BIM_EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "BIM_DEFAULT_FROM_EMAIL",
    "BIM Nexus <noreply@bimpos.com>",
)
BIM_ADMIN_EMAIL = os.environ.get(
    "BIM_ADMIN_EMAIL",
    "jad.alasmar@bimpos.com",
)

BIM_VITE_DEV_SERVER = os.environ.get(
    "BIM_VITE_DEV_SERVER",
    "",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
