import {
  ArrowRightLeft,
  BarChart3,
  BookOpen,
  Box,
  Camera,
  Check,
  CheckCircle2,
  ChevronRight,
  Circle,
  ClipboardList,
  Clock3,
  Cpu,
  Database,
  Download,
  Edit3,
  Eye,
  EyeOff,
  Filter,
  Handshake,
  LayoutDashboard,
  Layers,
  Menu,
  Moon,
  MoreHorizontal,
  Package,
  PackageCheck,
  PackagePlus,
  PackageX,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  ShieldAlert,
  ShoppingBag,
  Sun,
  Truck,
  TrendingUp,
  TriangleAlert,
  Upload,
  UserCheck,
  Users,
  Wrench,
  X
} from "lucide-react";

export {
  Camera,
  Check,
  ChevronRight,
  Circle,
  Edit3,
  Eye,
  EyeOff,
  Filter,
  LayoutDashboard,
  Menu,
  Moon,
  Package,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Sun,
  X
};

export const iconComponents = {
  "arrow-right-left": ArrowRightLeft,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  box: Box,
  "check-circle-2": CheckCircle2,
  clipboard: ClipboardList,
  "clock-3": Clock3,
  cpu: Cpu,
  database: Database,
  download: Download,
  delivery: Truck,
  "layout-dashboard": LayoutDashboard,
  layers: Layers,
  more: MoreHorizontal,
  package: Package,
  "package-check": PackageCheck,
  "package-plus": PackagePlus,
  "package-x": PackageX,
  plus: Plus,
  receiving: Download,
  reset: RotateCcw,
  save: Save,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shopping-bag": ShoppingBag,
  suppliers: Handshake,
  clients: Users,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  upload: Upload,
  "user-check": UserCheck,
  wrench: Wrench
};
