# Generated by Django 6.0.4 on 2026-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0003_rename_reportcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='modelname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
