# Generated by Django 6.0.4 on 2026-05-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0004_alter_category_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bim_stock.brand'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='modelname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('brand', 'modelname')},
        ),
    ]
