# Generated by Codex on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


def copy_product_type_to_category(apps, schema_editor):
    Type = apps.get_model("bim_stock", "Type")
    Category = apps.get_model("bim_stock", "Category")
    Product = apps.get_model("bim_stock", "Product")

    fallback_type, _ = Type.objects.get_or_create(name="General")

    for category in Category.objects.all():
        product = (
            Product.objects.filter(category_id=category.id, type_id__isnull=False)
            .order_by("id")
            .first()
        )
        category.type_id = product.type_id if product else fallback_type.id
        category.save(update_fields=["type"])


class Migration(migrations.Migration):

    dependencies = [
        ("bim_stock", "0007_product_unique_product_brand_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="bim_stock.type",
            ),
        ),
        migrations.RunPython(copy_product_type_to_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="bim_stock.type",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="bim_stock.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="bim_stock.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="bim_stock.productmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productmodel",
            unique_together=set(),
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_product_brand_model",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("type", "name"),
                name="unique_category_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("brand", "modelname"),
                name="unique_model_per_brand",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("category", "model"),
                name="unique_product_category_model",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
    ]
