# Generated by Django 6.0.4 on 2026-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0009_productunit_notes_productunit_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
