# Generated by Django 6.0.4 on 2026-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0010_productunit_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('returned', 'Returned'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
