# Generated by Django 6.0.4 on 2026-06-14 17:07

from django.db import migrations, models


def convert_damaged_units_to_inactive(apps, schema_editor):
    ProductUnit = apps.get_model("bim_stock", "ProductUnit")
    ProductUnit.objects.filter(status="damaged").update(status="inactive")


class Migration(migrations.Migration):

    dependencies = [
        ('bim_stock', '0011_alter_productunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            convert_damaged_units_to_inactive,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
