# Generated by Codex on 2026-06-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bim_stock", "0014_remove_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="minimum_stock_level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="printed",
        ),
    ]
